# Site settings
title: "Social Ventures"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: alb@andrewlb.com
description: > 
  Writing from 2017/2018 New America Public Interest Tech fellowship
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pit.andrewlb.com"

permalink: :url/

# Build settings
markdown: kramdown
highlight: rouge
paginate: 20
paginate_path: /page:num/


# Tracker
analytics: UA-11256323-6

#CSS
sass:
  style: compressed


include: [_pages]

plugins: [jekyll-paginate, jekyll-seo-tag]